# Generated by Django 4.0.2 on 2022-03-07 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='count',
            field=models.TextField(default=''),
        ),
    ]
