# Generated by Django 4.0.2 on 2022-03-04 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_category_image_product_color_product_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.AddField(
            model_name='category',
            name='catimage',
            field=models.ImageField(default='', height_field=100, upload_to='uploaded/', width_field=100),
        ),
    ]
