# Generated by Django 4.0.2 on 2022-03-06 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_product_color_remove_product_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='product',
        ),
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
